spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: auth-application
  security:
    user:
      name: user
      password: user
server:
  servlet:
    session:
      cookie:
        same-site: strict
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html